### ISSUE TITLE
Support other/mix animations

### ISSUE THREAD

**Issue by mohamad-amin** [florent37/ExpectAnim#13]
Hi.
Thank you for this great library, it makes writing animations extremely easy and saves a lot of time.
Could you please add some other animations like [these](https://github.com/daimajia/AndroidViewAnimations) ones or help me on how can I implement it?
And the possibility of mixing them together, like fading in a view while playing ZoomIn technique on it.
Again thanks for your great contribution :)

**Comment by TheWhiteLlama** [comment]
You can actually combine animations already :)
Just add those Expectations in toBe:

for example:
`new ExpectAnim().expect(view).toBe(invisible(),  scale(1.5f, 1.5f)).toAnimation().start();`

**Comment by florent37** [comment]
thx @TheWhiteLlama  👍

**Comment by mohamad-amin** [comment]
Thanks.
Yeah i knew about the combination but what about adding other animations as I mentioned? 
Like [these](https://github.com/daimajia/AndroidViewAnimations) ?
