### ISSUE TITLE
Version 1.0.2 found on jitpack

### ISSUE THREAD

**Issue by TheWhiteLlama** [florent37/ExpectAnim#16]
Hi there! It's me again ;)

I tried to compile the newest version via the compile statement, but it won't find 1.0.2. Not sure what causes the issue, but it might be due a missing tag or something?

**Comment by florent37** [comment]
it's not on jitpack but on jcenter

https://bintray.com/florent37/maven/ExpectAnim/1.0.2#files/com/github/florent37/expectanim/1.0.2
