### ISSUE TITLE
not found the lib

### ISSUE THREAD

**Issue by songsh** [florent37/ExpectAnim#17]
Error:(178, 13) Failed to resolve: com.github.florent37:expectanim:1.0.2
<a href="openFile:C:/Users/91489/AndroidStudioProjects/Gdzx_androidv1.0/ZhiXun/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by carmas123** [comment]
+1

**Comment by BigEnergys** [comment]
+1

**Comment by arybin-cn** [comment]
The same problem to me, solved by using:
compile 'com.github.florent37:expectanim:1.0.1'

**Comment by florent37** [comment]
fixed 👍
