### ISSUE TITLE
Can support rotation?

### ISSUE THREAD

**Issue by sorosunrain** [florent37/ExpectAnim#2]
Can support rotation?

**Comment by florent37** [comment]
in progress 👍 
will be on the futur release

**Comment by sorosunrain** [comment]
public class RotationAnimExpectation extends CustomAnimExpectation {

    private final float rotation;

    public RotationAnimExpectation(float rotation) {
        this.rotation = rotation;
    }

    @Override
    public Animator getAnimator(View viewToMove) {
        final ObjectAnimator objectAnimator = ObjectAnimator.ofFloat(viewToMove, "rotation", viewToMove.getRotation(), rotation);
        return objectAnimator;
    }
}

**Comment by florent37** [comment]
yes you can use it for now

**Comment by florent37** [comment]
But I want to add some enhancement, like to calculate the width of a rotated view, to add your view  on right for example

**Comment by florent37** [comment]
like this 😄 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5754972/23253639/9352d926-f9b5-11e6-99b7-a37180faaa93.gif)

**Comment by florent37** [comment]
will be on next release
