### ISSUE TITLE
Suggest adding proguard rules to readme

### ISSUE THREAD

**Issue by mirrajabi** [florent37/ExpectAnim#21]
Getting the following error while using proguard.

`Warning:com.github.florent37.expectanim.core.Expectations: can't find referenced class com.github.florent37.expectanim.core.Expectations$GravityIntDef`

It can be fixed by adding the below lines in `proguard-rules.pro` file
```
-keep class com.github.florent37.expectanim.*{ *; }
-dontwarn com.github.florent37.expectanim.**
```

**Comment by florent37** [comment]
thanls 👍
