### ISSUE TITLE
Add Visibility GONE when alpha is 0f

### ISSUE THREAD

**Issue by carmas123** [florent37/ExpectAnim#22]
@florent37 please can you add an option that set the view visibility to GONE when use the 
Expectations.alpha(0f) or Expectations.invisible?
This because a view with alpha 0f can be touched and clicked by user and send the onClick or touch events.

Thank you

**Comment by florent37** [comment]
Yes it's a good idea, 
In View.java, Visibility.GONE change the position of the view or just height / width ?

**Comment by florent37** [comment]
View.INVISIBLE is a better solution

**Comment by florent37** [comment]
can you try with 1.0.3 ?
