### ISSUE TITLE
Huge lag running the project

### ISSUE THREAD

**Issue by DanteAndroid** [florent37/ExpectAnim#3]
I'm not sure what I configure is wrong, but when I check out the project from Github, then run it in Android Emulator and on the real device, the animation runs with huge lag.

**Comment by florent37** [comment]
can you try on a physical device ?

**Comment by DanteAndroid** [comment]
I'm sorry, am I not clear? I tried
>in Android Emulator **and on the real device**
And I try 2 physical devices, both with huge lag. (Animation runs very slowly)
I think your lib's API is cool, and this is weird.
