### ISSUE TITLE
Visibility of view

### ISSUE THREAD

**Issue by anandpatole** [florent37/ExpectAnim#4]
Not an issue but on loading of screen invisible method displays view and then makes it invisible .

**Comment by florent37** [comment]
when you use `.start` or `.setNow` ?

**Comment by anandpatole** [comment]
.setNow

**Comment by anandpatole** [comment]
Since setNow method  execute after draw ,i m setting visibility gone before that method and making it visible whenever needed

**Comment by florent37** [comment]
ok :/ I will try to change that
