### ISSUE TITLE
the background of user contents is not being resized

### ISSUE THREAD

**Issue by arshadalisoomro** [florent37/ExpectAnim#8]
I saw your post on Google plus and found this lib a great resource to use in my future project, I forked and imported in Android Studio, I wanted the result as shown here 

[![gif](https://raw.githubusercontent.com/florent37/ExpectAnim/master/media/scroll.gif)

on my device I got this 
![some](https://cloud.githubusercontent.com/assets/2489546/23333503/591e6f18-fbae-11e6-8f83-594a3e78055e.gif)

the background of user contents is not being resized as shown in first git demo, how can I solve this issue please help...

**Comment by florent37** [comment]
What's your phone and Os version ?

**Comment by arshadalisoomro** [comment]
OS version is Android 5.1.1
And Phone is QMobile M350

**Comment by arshadalisoomro** [comment]
Any solution to this  issue?

**Comment by florent37** [comment]
I tried on a 4.4 and it works fine...
