### ISSUE TITLE
Gradle instruction readme.md fix

### ISSUE THREAD

**Issue by TheWhiteLlama** [florent37/ExpectAnim#9]
Hi there!

I love your library from the first sight. But it might be that there are users that won't be able to correctly install your app via gradle since the gradle compile statement is not correct in the readme.md file.

Instead of using
`compile 'com.github.florent37:expectanim:v1.0.1'`
the `v` is missing and it is stated to use
`compile 'com.github.florent37:expectanim:1.0.1'`

Keep on the great work!

**Comment by florent37** [comment]
where ?

**Comment by TheWhiteLlama** [comment]
I've made a pull request with to minor changes in the readme.md :)

**Comment by florent37** [comment]
:)
